name: pr-file-check

on:
  pull_request:
    types:
      - review_requested
      - synchronize # Checks any commits made to the PR

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
      - name: Check changed files
        uses: actions-cool/verify-files-modify@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          forbid-files: "docs/index.html, docs/home.md, requirements.txt, CNAME, LICENSE"
          forbid-paths: "docs/_logos/, images"
          # Disables closing the PR if the checks pass
          close: false
